### ISSUE TITLE
Feature: replace `jsbn` with native `BigInt`

### ISSUE THREAD

**Issue by mahnunchik** [beaugunderson/ip-address#169]
It would be nice to replace `jsbn` with native `BigInt`.

It is widely supported even in browsers https://caniuse.com/bigint

**Comment by robmanganelly** [comment]
Please consider also provide a proper implementation of toJSON that doesn't expose `bigint`. This is forcing consumers to implement themselves, because JSON.stringify does not understand bigints,

Thanks for the great job guys

**Comment by silverwind** [comment]
> Please consider (when you are taking this step) also providing a proper implementation of toJSON that doesn't expose `bigint`. This is forcing consumers to implement themselves, because JSON.stringify cannot serialize bigints, Curent implementation has this issue too.
> 
> Thanks for the great job guys

You can easily serialize bigint into JSON:

```js
JSON.stringify(obj, (_, v) => typeof v === 'bigint' ? v.toString() : v)
```

**Comment by robmanganelly** [comment]
Yes it can be done, but it means that you could inadvertently break something down the stream. It happened to me and I ended patching my serializer with a custom replacer, and it also happened on another project, which ended with a slightly different version of the replacer. This mean that the same class might have a different serialization in every project, which is not ideal IMHO. This is why added the recommendation, because that way you will ensure that the class gets serialized in the same way in every place, and can define your own rules for hydration, perhaps with static methods, or any other variant. ensuring consistency at the end of the day.
